
services:

  # Ad block
  # https://github.com/pi-hole/docker-pi-hole
  pihole:
    image: pihole/pihole:latest
    container_name: pihole

    environment:
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - ServerIP=${PIHOLE_SERVERIP}   # Address of Pi-hole host
      - VIRTUAL_HOST=pihole.home.lan
      - PIHOLE_DNS_1=1.1.1.3  # Cloudflare DNS - No Malware or Adult Content
      - PIHOLE_DNS_2=1.0.0.3  # Cloudflare DNS - Secondary, No Malware or Adult Content
      - TZ=${TZ}

    volumes:
      - '~/mounts/pihole/etc-pihole:/etc/pihole'
      - '~/mounts/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.3
      - 1.0.0.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  # Pi-hole block notifier
  pihole-notifier:
    depends_on:
      - pihole
    container_name: pihole-notifier
    build: pihole-notifier
    volumes:
      - ~/mounts/pihole/etc-pihole:/etc/pihole
      - ~/mounts/notifier/etc-eero:/etc/eero
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FTL_DB_FILE=/etc/pihole/pihole-FTL.db
      - MAIL_SENDER=${MAIL_SENDER}
      - MAIL_RECIPIENTS=${MAIL_RECIPIENTS}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - NOTIFIER_WHITELIST=${NOTIFIER_WHITELIST}
      - TZ=${TZ}

    restart: unless-stopped

  # VPN
  # https://github.com/wg-easy/wg-easy
  wireguard:
    depends_on:
      - pihole
    environment:
      # Server's hostname (clients will connect to):
      - WG_HOST=${WIREGUARD_HOST}
      - PASSWORD=${WIREGUARD_PASSWORD}

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.2
      - WG_DEFAULT_ADDRESS=10.8.0.x

      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2

      - TZ=${TZ}
    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    volumes:
      - ~/mounts/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

  # Dynamic DNS updater
  # https://github.com/troglobit/inadyn
  inadyn:
    image: troglobit/inadyn:latest
    container_name: inadyn
    environment:
      - TZ=${TZ}
    volumes:
      # This file should be created in advance!
      - ~/mounts/inadyn/inadyn.conf:/etc/inadyn.conf

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24

