---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Kylo
showStats: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
