# yaml-language-server: $schema=http://kylo.home:5000/api/config/schema.json
mqtt:
  enabled: false

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER_TAPO}:{FRIGATE_RTSP_PASS_TAPO}@192.168.4.176/stream1
          roles:
            - record
            - audio
        - path: rtsp://{FRIGATE_RTSP_USER_TAPO}:{FRIGATE_RTSP_PASS_TAPO}@192.168.4.176/stream2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    onvif:
      host: 192.168.4.176
      port: 2020
      user: '{FRIGATE_RTSP_USER_TAPO}'
      password: '{FRIGATE_RTSP_PASS_TAPO}'

  porch:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER_TAPO}:{FRIGATE_RTSP_PASS_TAPO}@192.168.4.210/stream1
          roles:
            - record
            - audio
        - path: rtsp://{FRIGATE_RTSP_USER_TAPO}:{FRIGATE_RTSP_PASS_TAPO}@192.168.4.210/stream2
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-aac

    onvif:
      host: 192.168.4.210
      port: 2020
      user: '{FRIGATE_RTSP_USER_TAPO}'
      password: '{FRIGATE_RTSP_PASS_TAPO}'

    zones:
      Walkway:
        coordinates: 0.907,0.995,0.589,0.312,0.284,0.222,0.264,0.998
        loitering_time: 0

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30
version: 0.15-1
